[project]
name = "ss26-ml-prozess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "lejepa",
    "marimo>=0.23.9",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "plotly>=6.8.0",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "torch>=2.12.0",
    "torchvision>=0.27.0",
]


[build-system]
requires = ["uv_build>=0.11.19,<0.12"]
build-backend = "uv_build"


[tool.marimo.runtime]
output_max_bytes = 100_000_000

[tool.uv.sources]
lejepa = { git = "https://github.com/galilai-group/lejepa" }
